apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hellojs-servicemonitor
  namespace: default
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: hellojs
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
